# Importing all Needed Libraries
from tkinter import *
from tkinter import ttk
from tkinter import Tk

MainScreen = Tk()
MainScreen.geometry('1200x720')
MainScreen.resizable(False , False)
MainScreen.title('Neural networks task')
#MainScreen.iconbitmap("AI.ico")
MainScreen.config(background='silver')
fr1  = Frame(width='1150',height='470',bg='white')
fr2  = Frame(fr1,width='500',height='180',bg='silver')
fr3  = Frame(fr1,width='570',height='180',bg='silver')
Lb1  = Label(fr1,text=' Welcome to neural networks task 1 ',fg='black',bg='silver',font=25,width=30)
Lb2  = Label(fr2,text=' Entre number of epochs ',fg='black',bg='white',font=15,width=25)
Lb3  = Label(fr2,text=' Enter MSE threshold ',fg='black',bg='white',font=15,width=25)
Lb4  = Label(fr2,text=' Enter learning rate  ',fg='black',bg='white',font=15,width=25)
Lb5  = Label(fr2,text=' Add bais  ',fg='black',bg='white',font=15,width=25)
Lb6  = Label(fr3,text =' Select two features  ',fg='black',bg='white',font=15,width=25)
Lb7  = Label(fr3,text =" Select two classes ",fg='black',bg='white',font=15,width=25)
Lb8  = Label(fr3,text =' Choose algorithm '  ,fg='black',bg='white',font=15,width=25)
En1 = Entry(fr2,fg='black',bg='white',font= 15,width=15)
En2 = Entry(fr2,fg='black',bg='white',font= 15,width=15)
En3 = Entry(fr2,fg='black',bg='white',font= 15,width=15)
selected_option = StringVar()
selected_option.set("Option 1")
radio1 = Radiobutton(fr2, text="Yes", variable=selected_option, value="Option 1")
radio2 = Radiobutton(fr2, text="No", variable=selected_option, value="Option 2")
radio1.place(x=320,y=140)
radio2.place(x=400,y=140)

fr1.place(x=25,y=20)
fr2.place(x=30,y=80)
fr3.place(x=550,y=80)
Lb1.place(x=360,y=20)
Lb2.place(x=40,y=20)
Lb3.place(x=40,y=60)
Lb4.place(x=40,y=100)
Lb5.place(x=40,y=140)
Lb6.place(x=40,y=20)
Lb7.place(x=40,y=80)
Lb8.place(x=40,y=140)
En1.place(x=320,y=20)
En2.place(x=320,y=60)
En3.place(x=320,y=100)
cmbo1 = ttk.Combobox(fr3, value = ('Culmen Length and Culmen Depth','Culmen Length and Flipper Length','Culmen Length and Body Mass','Culmen Length and Origin Location','Culmen Depth and Flipper Length','Culmen Depth and Body Mass','Culmen Depth and Culmen Origin Location','Flipper Length and Body Mass','Flipper Length and Origin Location','Origin Location and Body Mass'))
cmbo1.set('Culmen Length')
cmbo1.place(x=300,y=20,height=20,width=250)
cmbo2 = ttk.Combobox(fr3, value = ('Adelie and Gentoo','Adelie and Chinstrap','Chinstrap and Gentoo'))
cmbo2.set('Adelie and Gentoo')
cmbo2.place(x=300,y=80,height=20,width=250)
cmbo3 = ttk.Combobox(fr3, value = ('Adaline','Perceptron'))
cmbo3.set('Perceptron')
cmbo3.place(x=300,y=140,height=20,width=250)
MainScreen.mainloop()